services:
  - type: web
    name: librechat-frontend
    env: node
    plan: free
    buildCommand: npm run frontend
    startCommand: npm run backend
    envVars:
      - key: 
      - key:  
      - key: 

  - type: web
    name: librechat-backend
    env: node
    buildCommand: npm install
    startCommand: npm run backend
    envVars:
      - key:  
      - key:  
      - key: 
      - key: 
       
