services:
  - type: web
    name: librechat-frontend
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build 
    startCommand: cd client && npm run preview-prod
    envVars:
      - key:  SUPABASE_URL
      - key:  SUPABASE_ANON_KEY
      - key:  OPENROUTER_API_KEY

  - type: web
    name: librechat-backend
    env: node
    buildCommand: npm install
    startCommand: npm run backend
    envVars:
      - key:  NEXTAUTH_SECRET
      - key:  SUPABASE_URL
      - key:  SUPABASE_ANON_KEY
      - key:  OPENROUTER_API_KEY
       
