services:
  - type: web
    name: LibreChat
    build:
      command: npm install && npm run frontend
    startCommand: npm run start
    env:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
      - key: OPENROUTER_API_KEY
