services:
  - type: web
    name: librechat
    runtime: node
    rootDir: LibreChat-main
    buildCommand: npm install && npm run frontend
    startCommand: npm start
    envVars:
      - key: CRYPT_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
